/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.90
 * Generated at: 2020-12-13 18:40:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class create_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Search Volunteer Listings</title>\n");
      out.write("<link href =\"main.css\" type =\"text/css\" rel =\"stylesheet\"/>\n");
      out.write("<style>\n");
      out.write("\t.smalltext{\n");
      out.write("\t\tfont-size: 14px;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<header>\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\n");
      out.write("\t\t\n");
      out.write(" </header>\n");
      out.write(" \t\n");
      out.write(" \t<br>\n");
      out.write("\t\n");
      out.write("\t<form action=\"CreateListing\" method=\"POST\">\n");
      out.write("\t  <label for=\"title\">Title of listing:</label>\n");
      out.write("\t  <input type=\"text\" id=\"title\" name=\"title\" required><br><br>\n");
      out.write("\t  \n");
      out.write("\t  <label for=\"category\">Category:</label>\n");
      out.write("\t  <select name=\"category\" id=\"category\">\n");
      out.write("\t  \t<option value=\"indoor\">Indoor</option>\n");
      out.write("\t  \t<option value=\"outdoor\">Outdoor</option>\n");
      out.write("\t  </select><br><br>\n");
      out.write("\t  \n");
      out.write("\t  <label for=\"desc\">Description:</label><br>\n");
      out.write("\t  <textarea rows = \"5\" cols = \"60\" name = \"desc\" id=\"desc\"></textarea><br><br>\n");
      out.write("\t  \n");
      out.write("\t  \n");
      out.write("\t  \n");
      out.write("\t  <label for=\"tags\">Tags:</label>\n");
      out.write("\t  <input type=\"text\" id=\"tags\" name=\"tags\">\n");
      out.write("\t  <p class=\"smalltext\">Please separate tags with a comma.</p><br><br>\n");
      out.write("\t  \n");
      out.write("\t  <input type=\"submit\" value=\"Submit\">\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<footer id=\"footer\">\n");
      out.write("\t\t<a href=\"aboutus.jsp\"> About Us</a><br>\n");
      out.write("\t\t<a href=\"mailto:jojoshackteam@gmail.com\">Send us an Email</a>\n");
      out.write("\t</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
